version: '3.4'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '21337:5432'
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: 'development'
      POSTGRES_DB: development
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 30s
      retries: 3
